import type { Recipe } from "./recipeTypes";

export function RecipeCard({ recipe, compact = false, onRun }: { recipe: Recipe; compact?: boolean; onRun: () => void }) {
  return <article className={`recipe-card ${compact ? "compact" : ""}`}><div className="recipe-card-top"><span className="recipe-symbol">{recipe.recipeKind === "true_3d" ? "3D" : recipe.recipeKind === "html_to_video" ? "&lt;/&gt;" : recipe.recipeKind === "voiceover_package" ? "VO" : recipe.recipeKind === "screen_demo" ? "REC" : recipe.recipeKind === "hybrid_2d_3d" ? "2+3" : "2D"}</span><span className={`availability ${recipe.localFirst ? "local" : "cloud"}`}>{recipe.localFirst ? "LOCAL" : "HYBRID"}</span></div><h4>{recipe.name}</h4><p>{recipe.worker}</p><div className="recipe-card-bottom"><span>{recipe.requiresApproval ? "Cần người dùng duyệt" : "Sẵn sàng"}</span><button className="small-button" onClick={onRun}>Chọn →</button></div></article>;
}

export function RecipeCatalog({ recipes, selectedRecipe, onSelect, onRun, onQueuePending }: { recipes: Recipe[]; selectedRecipe: string; onSelect: (value: string) => void; onRun: (recipe: Recipe) => void; onQueuePending: (recipe: Recipe) => void }) {
  const current = recipes.find((recipe) => recipe.recipeKind === selectedRecipe) ?? recipes[0];
  return <section className="catalog-layout"><div className="panel catalog-list"><div className="section-heading"><div><p className="eyebrow">DANH MỤC QUY TRÌNH</p><h3>Định dạng video</h3></div><span className="count-chip">{recipes.length} quy trình</span></div><div className="recipe-list">{recipes.map((recipe) => <button key={recipe.recipeKind} className={`recipe-list-item ${selectedRecipe === recipe.recipeKind ? "selected" : ""}`} onClick={() => onSelect(recipe.recipeKind)}><span className="list-symbol">{recipe.recipeKind === "true_3d" ? "3D" : recipe.recipeKind === "html_to_video" ? "</>" : "01"}</span><span><strong>{recipe.name}</strong><small>{recipe.worker}</small></span><span className="chevron">→</span></button>)}</div></div><div className="panel recipe-detail"><p className="eyebrow">QUY TRÌNH ĐANG CHỌN</p><div className="detail-symbol">{current?.recipeKind === "true_3d" ? "3D" : "A3"}</div><h3>{current?.name}</h3><p className="detail-copy">Quy trình này đi qua luồng chuẩn hóa: kiểm tra tài sản và quyền → timeline → bộ xử lý chuyên biệt → âm thanh/phụ đề → xuất bằng FFmpeg → người dùng duyệt.</p><div className="detail-facts"><div><span>Bộ xử lý</span><strong>{current?.worker}</strong></div><div><span>Thực thi</span><strong>{current?.localFirst ? "Ưu tiên cục bộ" : "Kết hợp / đám mây"}</strong></div><div><span>Phê duyệt</span><strong>Người dùng duyệt</strong></div></div><button className="primary-button wide" onClick={() => current && onRun(current)}>Chạy bản xem trước mô phỏng <span>→</span></button><button className="secondary-button wide" onClick={() => current && onQueuePending(current)}>Tạo tác vụ chờ an toàn</button><p className="detail-note">Bản xem trước mô phỏng chỉ kiểm tra trạng thái; tác vụ chờ chỉ ghi nhận trạng thái để chuẩn bị attempt, không gọi API và không chạy Blender/FFmpeg thật.</p></div></section>;
}
