import type { Attempt, AttemptOutput, ExecutableId, Job, JobAction, MediaKind, WorkerLaunchPlan } from "./jobsTypes";
import type { Project } from "../shared/projectTypes";
import { EmptyState } from "../shared/ui";

function displayJobState(value: string) {
  const labels: Record<string, string> = { queued: "Đang chờ", running: "Đang chạy", succeeded: "Thành công", failed: "Thất bại", cancelled: "Đã hủy", cancel_requested: "Đang yêu cầu hủy", pending: "Chờ chuẩn bị", reconciliation_required: "Cần đối chiếu" };
  return labels[value] ?? value;
}

export function JobsPanel({ jobs, projects, attempts, attemptOutputs, launchPlan, attemptJobId, attemptExecutableId, attemptOutputPath, attemptMediaKind, onAttemptExecutableChange, onAttemptOutputPathChange, onAttemptMediaKindChange, onAction, onInspect, onPrepareAttempt, onStartMockAttempt, onPreviewLaunch }: { jobs: Job[]; projects: Project[]; attempts: Attempt[]; attemptOutputs: AttemptOutput[]; launchPlan: WorkerLaunchPlan | null; attemptJobId: string; attemptExecutableId: ExecutableId | ""; attemptOutputPath: string; attemptMediaKind: MediaKind; onAttemptExecutableChange: (value: ExecutableId | "") => void; onAttemptOutputPathChange: (value: string) => void; onAttemptMediaKindChange: (value: MediaKind) => void; onAction: (action: JobAction, jobId: string) => void; onInspect: (jobId: string) => void; onPrepareAttempt: (jobId: string) => void; onStartMockAttempt: (attemptId: string, jobId: string) => void; onPreviewLaunch: (attemptId: string) => void }) {
  return <section className="panel page-panel"><div className="section-heading"><div><p className="eyebrow">LỊCH SỬ TÁC VỤ BỀN VỮNG</p><h3>Hàng đợi và lịch sử tác vụ</h3><p className="section-subtitle">Bộ xử lý mô phỏng cục bộ có lease/heartbeat/hủy; tác vụ FFmpeg dùng tham số cố định; bộ xử lý bên ngoài tổng quát vẫn bị khóa.</p></div><button className="secondary-button">Bộ lọc</button></div><div className="attempt-config"><div><p className="eyebrow">CẤU HÌNH LẦN CHẠY CHỜ</p><strong>Cấu hình bằng chứng trước khi chuẩn bị</strong><span>Chỉ ghi thông tin đầu ra dự kiến; không khởi chạy chương trình.</span></div><label>Chương trình<select value={attemptExecutableId} onChange={(event) => onAttemptExecutableChange(event.target.value as ExecutableId | "")}><option value="">Chưa chọn</option><option value="ffmpeg">FFmpeg</option><option value="ffprobe">FFprobe</option><option value="blender">Blender</option><option value="node">Node</option><option value="python">Python</option><option value="obs">OBS</option></select></label><label>Loại phương tiện<select value={attemptMediaKind} onChange={(event) => onAttemptMediaKindChange(event.target.value as MediaKind)}><option value="video">Video</option><option value="audio">Audio</option><option value="image">Image</option><option value="subtitle">Subtitle</option><option value="thumbnail">Thumbnail</option><option value="metadata">Metadata</option><option value="image_sequence">Image sequence</option></select></label><label>Đường dẫn đầu ra dự kiến<input value={attemptOutputPath} onChange={(event) => onAttemptOutputPathChange(event.target.value)} placeholder="preview.mp4" /></label></div>{jobs.length === 0 ? <EmptyState label="Hàng đợi đang trống" detail="Chạy một recipe từ mục Quy trình video để tạo mock job." /> : <div className="job-table"><div className="provider-head"><span>Mã tác vụ</span><span>Quy trình</span><span>Dự án</span><span>Trạng thái</span><span>Tiến độ</span></div>{jobs.map((job) => <div className="provider-row" key={job.jobId}><strong className="mono">{job.jobId}</strong><span>{job.kind}</span><span>{projects.find((project) => project.projectId === job.projectId)?.name ?? job.projectId}</span><span className="status-text enabled">{displayJobState(job.state)}</span><span><div className="progress-track"><i style={{ width: `${job.progress * 100}%` }} /></div>{Math.round(job.progress * 100)}% {job.state === "failed" && <button className="small-button" onClick={() => onAction("retry_job", job.jobId)}>Thử lại</button>}{["queued", "running", "cancel_requested"].includes(job.state) && <button className="small-button danger" onClick={() => onAction("cancel_job", job.jobId)}>Hủy</button>}<button className="small-button" onClick={() => onInspect(job.jobId)}>Lần chạy</button>{job.state === "queued" && <button className="small-button" onClick={() => onPrepareAttempt(job.jobId)}>Chuẩn bị lần chạy</button>}</span></div>)}</div>}
      {attemptJobId && <div className="attempt-panel"><div className="attempt-panel-heading"><div><p className="eyebrow">BẰNG CHỨNG THỰC THI</p><h4>Các lần chạy của {attemptJobId}</h4></div><span className="count-chip">{attempts.length}</span></div>{attempts.length === 0 ? <p className="attempt-empty">Chưa có lần chạy nào được lưu cho tác vụ này.</p> : <div className="attempt-list">{attempts.map((attempt) => <div className="attempt-row" key={attempt.attemptId}><strong className="mono">#{attempt.attemptNumber}</strong><span className="status-text enabled">{displayJobState(attempt.state)}</span><span>{attempt.executionMode === "in_process_mock" ? "bộ xử lý mô phỏng cục bộ" : (attempt.executableId ?? "chưa chọn chương trình")}</span><span>chờ tối đa {attempt.timeoutSeconds} giây</span><span>{attempt.processStarted ? (attempt.executionMode === "external_process" ? "Đã chạy chương trình bên ngoài" : "Đã chạy bộ xử lý mô phỏng") : "Chưa chạy chương trình"} · tác động ngoài chưa rõ: {attempt.externalSideEffectUnknown ? "có" : "không"} {attempt.state === "pending" && <button className="small-button" onClick={() => onStartMockAttempt(attempt.attemptId, attempt.jobId)}>Chạy bộ xử lý mô phỏng</button>}<button className="small-button" onClick={() => onPreviewLaunch(attempt.attemptId)}>Kế hoạch khởi chạy</button></span></div>)}</div>}{launchPlan && <div className="launch-plan"><div><strong>Worker launch plan · attempt #{launchPlan.attemptNumber}</strong><span>{launchPlan.executableId ?? "chưa chọn executable"} · {launchPlan.timeoutSeconds}s · {launchPlan.expectedOutputCount} expected outputs</span></div><b>{launchPlan.canStart ? "READY" : "BLOCKED"}</b><p>{launchPlan.blockers.join(" · ")}</p></div>}{attemptOutputs.length > 0 && <div className="attempt-output-list"><p className="eyebrow">ĐẦU RA DỰ KIẾN / LẦN CHẠY MỚI NHẤT</p>{attemptOutputs.map((output) => <div className="attempt-output-row" key={output.outputId}><span className="mono">{output.relativePath}</span><span>{output.mediaKind}</span><span className="status-text enabled">{output.validationState}</span></div>)}</div>}<p className="attempt-note">Bộ xử lý mô phỏng chạy trong ứng dụng để kiểm thử lease, heartbeat và hủy phối hợp. Tác vụ FFmpeg cố định là đường chạy bên ngoài duy nhất đang bật; Blender, ComfyUI và xử lý phương tiện của người dùng vẫn cần cổng an toàn tiếp theo.</p></div>}
    </section>;
}

export function ActivityRow({ job }: { job: Job }) {
  return <div className="activity-row"><span className="activity-dot" /><div><strong>{job.kind}</strong><span>{displayJobState(job.state)} · {job.attemptCount} lần chạy</span></div><span className="activity-time">#{job.jobId.slice(-4)}</span></div>;
}
