import type { NarrativeVisualPlanPreview } from "./reviewTypes";

export function ReviewPanel({ preview, onPreview }: { preview: NarrativeVisualPlanPreview | null; onPreview: () => void }) {
  return <section className="review-grid"><div className="panel review-main"><p className="eyebrow">DUYỆT HÌNH ẢNH THEO NỘI DUNG</p><div className="section-heading"><div><h3>{preview ? `Đã biên dịch ${preview.beats.length} nhịp cảnh` : "Chưa có bản xem trước kế hoạch hình ảnh"}</h3><p>{preview ? `${preview.planId} · ${preview.language} · ${preview.aspectRatio} · ${preview.totalDurationFrames} khung hình` : "Biên dịch fixture để kiểm tra độ phủ lời dẫn, tính liên tục của chủ thể, bằng chứng hình ảnh và prompt trước khi tạo."}</p></div><button className="secondary-button" onClick={onPreview}>{preview ? "Biên dịch lại" : "Biên dịch kế hoạch hình ảnh"}</button></div>{preview && <div className="visual-plan-list">{preview.beats.map((beat) => <article className="visual-plan-beat" key={beat.beatId}><div className="visual-plan-beat-head"><strong>{beat.beatId}</strong><span>{beat.startFrame}–{beat.endFrame}f · {beat.durationFrames}f</span><span className="status-text disabled">{beat.reviewDecision}</span></div><p className="visual-plan-narration">{beat.narrationText}</p><div className="visual-plan-grid"><div><small>Khẳng định nội dung</small><span>{beat.narrativeClaim}</span></div><div><small>Ý định hình ảnh</small><span>{beat.visualIntent}</span></div><div><small>Chủ thể / điểm neo</small><span>{beat.entities.map((entity) => `${entity.name}: ${entity.identityAnchors.join(" · ")}`).join(" | ")}</span></div><div><small>Bằng chứng hình ảnh</small><span>{beat.requiredVisualElements.join(" · ")}</span></div><div><small>Tài sản dự kiến</small><span className="mono">{beat.expectedAssetPath}</span></div><div><small>Trạng thái</small><span>{beat.candidateState} · semantic {beat.semanticState} · continuity {beat.continuityState} · rights {beat.rightsState}</span></div></div><details><summary>Xem prompt có căn cứ</summary><p><strong>Tích cực:</strong> {beat.positivePrompt}</p><p><strong>Loại trừ:</strong> {beat.negativePrompt}</p></details></article>)}</div>}<p className="attempt-note">{preview?.message ?? "Bản xem trước không khởi chạy chương trình: không tạo video, không gọi mạng, không đăng bài, không phát sinh chi phí."}</p></div><div className="panel checklist-panel"><p className="eyebrow">DANH SÁCH KIỂM TRA</p><CheckItem label="Quyền sở hữu / giấy phép tài sản" /><CheckItem label="Cho phép dùng giọng / diện mạo" /><CheckItem label="Quyết định công bố nội dung AI" /><CheckItem label="Phụ đề và khả năng tiếp cận" /><CheckItem label="Thiết lập bàn giao cho nền tảng" /><p className="attempt-note">Mỗi nhịp cảnh phải đạt mức liên quan nội dung và tính liên tục trước khi chọn phương án. Chữ chính xác nên thêm bằng lớp phủ cố định, không phụ thuộc ảnh AI.</p></div></section>;
}

function CheckItem({ label }: { label: string }) {
  return <div className="check-item"><span className="empty-check" />{label}<span className="pending-text">ĐANG CHỜ</span></div>;
}
